name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-build-rails-main-ruby-2.7.2-${{ hashFiles('**/Gemfile.lock') }}
    - name: Lint with Rubocop
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rubocop
  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: [5.2.6, 6.0.4.7, 6.1.4.7, 7.0.2.3]
        ruby_version: [2.5.9, 2.6.8, 2.7.4, 3.0.3, 3.1.1]
        exclude:
          - rails_version: 5.2.6
            ruby_version: 3.0.3
          - rails_version: 6.0.4.7
            ruby_version: 3.0.3
          - rails_version: 7.0.2.3
            ruby_version: 2.5.9
          - rails_version: 7.0.2.3
            ruby_version: 2.6.8
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-build-rails-${{ matrix.rails_version }}-ruby-${{ matrix.ruby_version }}-${{ hashFiles('**/Gemfile.lock') }}
    - name: Build and test with RSpec
      run: |
        bundle config path vendor/bundle
        bundle update
        bundle install --jobs 4 --retry 3
        bundle exec rspec
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
    - name: Upload coverage results
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: simplecov-resultset-rails${{matrix.rails_version}}-ruby${{matrix.ruby_version}}
        path: coverage
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Download coverage results
      uses: actions/download-artifact@v2
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-build-rails-main-ruby-2.7.2-${{ hashFiles('**/Gemfile.lock') }}
    - name: Collate simplecov
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rake coverage:report

